// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKDN_i_Q85IRQbgqu4L7DoECDznDgY-g',
    appId: '1:503252170233:web:7bcaeace6ebaae8f55f928',
    messagingSenderId: '503252170233',
    projectId: 'talko-8d370',
    authDomain: 'talko-8d370.firebaseapp.com',
    storageBucket: 'talko-8d370.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbr1sMRt063Zdsn-_9NNxheFJyne3b1UA',
    appId: '1:503252170233:android:feb7e93fe97aef3e55f928',
    messagingSenderId: '503252170233',
    projectId: 'talko-8d370',
    storageBucket: 'talko-8d370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYciWRaPQe9uyg02l9u4JRwMlvxtk0vbA',
    appId: '1:503252170233:ios:b4934e803efbd73655f928',
    messagingSenderId: '503252170233',
    projectId: 'talko-8d370',
    storageBucket: 'talko-8d370.firebasestorage.app',
    iosBundleId: 'com.example.talkoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYciWRaPQe9uyg02l9u4JRwMlvxtk0vbA',
    appId: '1:503252170233:ios:b4934e803efbd73655f928',
    messagingSenderId: '503252170233',
    projectId: 'talko-8d370',
    storageBucket: 'talko-8d370.firebasestorage.app',
    iosBundleId: 'com.example.talkoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkKDN_i_Q85IRQbgqu4L7DoECDznDgY-g',
    appId: '1:503252170233:web:4e62076a45c632ac55f928',
    messagingSenderId: '503252170233',
    projectId: 'talko-8d370',
    authDomain: 'talko-8d370.firebaseapp.com',
    storageBucket: 'talko-8d370.firebasestorage.app',
  );
}
